### ISSUE TITLE
Simplify the scripts in package.json

### ISSUE THREAD

**Issue by Kachulio1** [Human-Connection/Nitro-Backend#130]
**Is your feature request related to a problem? Please describe.**
   it's kind of difficult to understand the scripts section in package.json

**Describe the solution you'd like**
  reuse some command to make the scripts cleaner

**Comment by roschaefer** [comment]
@Kachulio1 together with @mattwr18 we spent 3 hours only on this task and we ran into a lot of issues. I'm closing this for now.

The current setup starts a `seeder` server and a server used for testing in another process. This is suboptimal. Ideally we would have everything in one process. In that case we could simplify the `package.json` but at the moment, I think we can not.
