### ISSUE TITLE
have documentation include getting started queries for the playground

### ISSUE THREAD

**Issue by tansaku** [Human-Connection/Nitro-Backend#144]
Arriving in the playground it's not immediately obvious what queries one can make.

![](https://dl.dropbox.com/s/7lr1emoa53j65zv/Screenshot%202019-02-04%2013.13.31.png?dl=0)

Would be great if examples were included, either in the docs or when the playground starts up (maybe it does once it is seeded?)  - There is something on this page in the docs:

https://docs.human-connection.org/nitro/backend/graphql-with-apollo

but would be great if there was something to copy and paste, or even something that just pops out when things start (apologies if there is already something like this after seeding)

**Comment by appinteractive** [comment]
There is a possibility in the latest GraphQL-Yoga Server to add predefined queries in the playground. That would be a good solution I think.

**Comment by roschaefer** [comment]
We should include images in the documentation. @tansaku e.g. if you click on the green "Schema" bookmark on the right side, that will give you an overview of the possibilities. Also, you can `Ctrl+Space` to get auto-completion in the query editor on the right side.

E.g. type in `{`, hit enter. Curly braces will be auto-closed. Hit `Ctrl+Space` and you get a dropdown of all the resources. The response of the server is also quite helpful, e.g. you have to request at least one attribute etc.

**Comment by tansaku** [comment]
That's good to know Robert - we could also provide some simple text queries like:

```
{
  Post {
    title
  }
}
```
to help folks get started ...

**Comment by roschaefer** [comment]
@tansaku I would call that a PR to our [documentation](https://github.com/Human-Connection/Nitro-Documentation) including a screenshot and a query for copy+paste :+1:

**Comment by Tirokk** [comment]
I have copy and paste this to documentation:
[https://github.com/Human-Connection/Nitro-Documentation/issues/26](https://github.com/Human-Connection/Nitro-Documentation/issues/26)
