### ISSUE TITLE
error trying to seed data

### ISSUE THREAD

**Issue by tansaku** [Human-Connection/Nitro-Backend#146]
**Describe the bug**
have upgraded to node 10.15 and updated `yarn run dev` works fine, but when I try `yarn run db:seed` I get the following error:

```
→ yarn run db:seed
yarn run v1.13.0
$ $npm_package_config_no_auth run-p --race dev db:script:seed
$ nodemon --exec babel-node src/
$ wait-on tcp:4001 && babel-node src/seed/seed-db.js
[nodemon] 1.18.9
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `babel-node src/`
{ Error: Network error: Response not successful: Received status code 400
    at new ApolloError (/Users/tansaku/Documents/GitHub/Human-Connection/Nitro-Backend/node_modules/src/errors/ApolloError.ts:56:5)
    at Object.error (/Users/tansaku/Documents/GitHub/Human-Connection/Nitro-Backend/node_modules/src/core/QueryManager.ts:292:13)
    at notifySubscription (/Users/tansaku/Documents/GitHub/Human-Connection/Nitro-Backend/node_modules/zen-observable/lib/Observable.js:134:18)
    at onNotify (/Users/tansaku/Documents/GitHub/Human-Connection/Nitro-Backend/node_modules/zen-observable/lib/Observable.js:165:3)
    at SubscriptionObserver.error (/Users/tansaku/Documents/GitHub/Human-Connection/Nitro-Backend/node_modules/zen-observable/lib/Observable.js:224:7)
    at /Users/tansaku/Documents/GitHub/Human-Connection/Nitro-Backend/node_modules/apollo-link-http/src/httpLink.ts:184:20
    at process._tickCallback (internal/process/next_tick.js:68:7)
  graphQLErrors: [],
  networkError:
   { ServerError: Response not successful: Received status code 400
       at throwServerError (/Users/tansaku/Documents/GitHub/Human-Connection/Nitro-Backend/node_modules/apollo-link-http-common/src/index.ts:113:17)
       at /Users/tansaku/Documents/GitHub/Human-Connection/Nitro-Backend/node_modules/apollo-link-http-common/src/index.ts:144:11
       at process._tickCallback (internal/process/next_tick.js:68:7)
     name: 'ServerError',
     response:
      Response {
        size: 0,
        timeout: 0,
        [Symbol(Body internals)]: [Object],
        [Symbol(Response internals)]: [Object] },
     statusCode: 400,
     result: { errors: [Array] } },
  message:
   'Network error: Response not successful: Received status code 400',
  extraInfo: undefined }
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "db:script:seed" exited with 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I just installed the Neo4j desktop and got it all running according to the instructions in the docs:

![](https://dl.dropbox.com/s/nkfsv61efx4jcjy/Screenshot%202019-02-05%2009.56.41.png?dl=0)

**Comment by mattwr18** [comment]
we ran into this issue to in our getting started pairing session http://youtu.be/ORVpvzf5Wzk... followed instructions on getting set up with neo4j Desktop and ran into the same issue when trying to seed the database... I have pulled down the latest changes from `master`, which were just changes to the `CODE_OF_CONDUCT.md` and run the seed operation locally and been unable to replicate the error. I am on a Linux, with the community edition. I also reset the database with no issue

**Comment by roschaefer** [comment]
@tansaku @mattwr18 did you create your local `.env` file and set the credentials accordingly?

**Comment by mattwr18** [comment]
My local setup is fine, and yes Luke set up neo4j and configured it with the username and password from the .env.template

**Comment by tansaku** [comment]
yes, I also followed those instructions precisely - although I note that I can't immediately find a way to reset the password in neo4j desktop

**Comment by Tirokk** [comment]
In my Neo4j Desktop version 1.1.13 on Mac there is an **Administration** tab additional at right side of the **Upgrade** tab where I can set a new password for the database … See screenshot …
![Screenshot on macOS](https://user-images.githubusercontent.com/25344101/52375260-826dbb80-2a5f-11e9-8c86-b0bcb45a4e71.png)

**Comment by lukegraphix** [comment]
I delete my project and set a new password in the .env. After that I create a new project in Neo4j Desktop on my Mac. Now the db:seed script was successfully. 
The "Set Database Password" on an already existing project in Neo4j Desktop has not working for me.

**Comment by tansaku** [comment]
thanks @Tirokk - that administration tab was concealed for me by screen wrapping - I've reset password, but that didn't help ...

I've tried what @lukegraphix did - and I don't think it worked for me - I have a new project, with everything created from scratch, new password, updated in .env.  The reset operation works but not db:seed ... the local graph is set to be running ... here's my .env

```
NEO4J_URI=bolt://localhost:7687
NEO4J_USER=neo4j
NEO4J_PASSWORD=123456
GRAPHQL_PORT=4000
GRAPHQL_URI=http://localhost:4000
CLIENT_URI=http://localhost:3000
MOCK=false
```

my port is 7687

```
[tansaku@Samuels-MBP:~/Documents/Github/Human-Connection/Nitro-Backend (master)]$ 
→ yarn run db:reset
yarn run v1.13.0
$ $npm_package_config_no_auth run-p --race dev db:script:reset
$ nodemon --exec babel-node src/
$ wait-on tcp:4001 && babel-node src/seed/reset-db.js
[nodemon] 1.18.9
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `babel-node src/`
Successfully deleted all nodes and relations!
✨  Done in 4.51s.
[tansaku@Samuels-MBP:~/Documents/Github/Human-Connection/Nitro-Backend (master)]$ 
→ yarn run db:seed
yarn run v1.13.0
$ $npm_package_config_no_auth run-p --race dev db:script:seed
$ nodemon --exec babel-node src/
$ wait-on tcp:4001 && babel-node src/seed/seed-db.js
[nodemon] 1.18.9
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `babel-node src/`
{ Error: Network error: Response not successful: Received status code 400
    at new ApolloError (/Users/tansaku/Documents/GitHub/Human-Connection/Nitro-Backend/node_modules/src/errors/ApolloError.ts:56:5)
    at Object.error (/Users/tansaku/Documents/GitHub/Human-Connection/Nitro-Backend/node_modules/src/core/QueryManager.ts:292:13)
    at notifySubscription (/Users/tansaku/Documents/GitHub/Human-Connection/Nitro-Backend/node_modules/zen-observable/lib/Observable.js:134:18)
    at onNotify (/Users/tansaku/Documents/GitHub/Human-Connection/Nitro-Backend/node_modules/zen-observable/lib/Observable.js:165:3)
    at SubscriptionObserver.error (/Users/tansaku/Documents/GitHub/Human-Connection/Nitro-Backend/node_modules/zen-observable/lib/Observable.js:224:7)
    at /Users/tansaku/Documents/GitHub/Human-Connection/Nitro-Backend/node_modules/apollo-link-http/src/httpLink.ts:184:20
    at process._tickCallback (internal/process/next_tick.js:68:7)
  graphQLErrors: [],
  networkError:
   { ServerError: Response not successful: Received status code 400
       at throwServerError (/Users/tansaku/Documents/GitHub/Human-Connection/Nitro-Backend/node_modules/apollo-link-http-common/src/index.ts:113:17)
       at /Users/tansaku/Documents/GitHub/Human-Connection/Nitro-Backend/node_modules/apollo-link-http-common/src/index.ts:144:11
       at process._tickCallback (internal/process/next_tick.js:68:7)
     name: 'ServerError',
     response:
      Response {
        size: 0,
        timeout: 0,
        [Symbol(Body internals)]: [Object],
        [Symbol(Response internals)]: [Object] },
     statusCode: 400,
     result: { errors: [Array] } },
  message:
   'Network error: Response not successful: Received status code 400',
  extraInfo: undefined }
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "db:script:seed" exited with 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I'm on High Sierra OSX 10.13.6
Neo4j Desktop 1.1.15

I've just pulled the latest from master, and rm -rf node_modules and run yarn to re-install everything - no joy ...

**Comment by appinteractive** [comment]
Is the database really running? (Play Button)

**Comment by Tirokk** [comment]
If you have your database started and run it by the play button can you reach it via the browser @tansaku ?
http://localhost:7474/browser/
Click on the top most symbol on the left. Then it must appear some info under **Database Information** + **Node Labels** etc.. Even if not seeded, it should be empty. But than it shows that you have contact to the DB via your browser. May be one step ahead …

**Comment by tansaku** [comment]
@Tirokk yes- that works fine and shows the database empty - seems that simply the seed operation itself can't connect for some reason ...

**Comment by Tirokk** [comment]
Hey @tansaku my `.env`is:

```
NEO4J_URI=bolt://localhost:7687
NEO4J_USER=neo4j
NEO4J_PASSWORD=letmein
GRAPHQL_PORT=4000
GRAPHQL_URI=http://localhost:4000
CLIENT_URI=http://localhost:3000
MOCK=false

JWT_SECRET="b/&&7b78BF&fv/Vd"
MAPBOX_TOKEN="pk.eyJ1IjoiaHVtYW4tY29ubmVjdGlvbiIsImEiOiJjajl0cnBubGoweTVlM3VwZ2lzNTNud3ZtIn0.KZ8KK9l70omjXbEkkbHGsQ"
```

My password is `letmein` for clarification.
Why you are using a different password as the standard one in the `.env.template` file?
That makes everything more inscrutable? Or not?
Has your Neo4j graph the same or fitting password?

**Comment by tansaku** [comment]
I started with letmein and that didn't work, and then I reset it following what @lukegraphix said about creating a new project from scratch, so I set a new password - I've tried a few variations ... i start to wonder about the project name and/or the username - it would be nice to trace the communication between the back end and neo4j to see what's actually being sent

I wonder if the neo4j username is fixed? I can't see any setting for it in desktop, or any way that the back end would determine which project in the desktop it accesses ...

**Comment by Tirokk** [comment]
So @lukegraphix was successful with a Docker Community installation as he wrote on Discord. May you could try that one too @tansaku ?
Or any further success or solution?

**Comment by tansaku** [comment]
I just updated to the latest master and using node 10.15 and it worked:

```
→ yarn run db:seed
yarn run v1.13.0
$ $npm_package_config_no_auth run-p --race dev db:script:seed
$ nodemon --exec babel-node src/
$ wait-on tcp:4001 && babel-node src/seed/seed-db.js
[nodemon] 1.18.10
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `babel-node src/`
Server ready at http://localhost:4001 🚀
Seeded Data...
✨  Done in 20.57s.
```

**Comment by Tirokk** [comment]
Yeah, great @tansaku !!! 🚀
