### ISSUE TITLE
Cannot run seed data - again

### ISSUE THREAD

**Issue by roschaefer** [Human-Connection/Nitro-Backend#17]
**Describe the bug**
The new permissions break the seed data. *Without seed data there is no way to let open source contributors contribute!*

**To Reproduce**
1. Run `docker-compose up`
2. Run `docker-compose exec backend yarn run seedDb`
3. Visit http://localhost:4000/
4. Type in: `query {  User {    email  } }`
5. Response: `{  "data": {    "User": []  } }`

**Expected behavior**
5. Response:
```json
{
  "data": {
    "User": [
      {
        "email": "moderator@example.org"
      },
      {
        "email": "user@example.org"
      },
      {
        "email": "angie@example.org"
      },
      {
        "email": "admin@example.org"
      }
    ]
  }
}
```

**Additional context**
Running the seeder gives me the following error:
```
Error: GraphQL error: 2 arguments required, but only 1 present
[...]
```

**Comment by appinteractive** [comment]
This is due to the fact that we now have authentification in place. We have to find a way to seed the data properly in this case, we had that discussion in the past.

At the moment I have no clue how to achieve that. Help is very welcome.
