### ISSUE TITLE
Create unit test for resolver CreateBadges

### ISSUE THREAD

**Issue by mattwr18** [Human-Connection/Nitro-Backend#194]
**Is your feature request related to a problem? Please describe.**
We want to whitelist the resolvers we need for our app, and have them unit tested
**Describe the solution you'd like**
Write a unit test to check the creation of badges, authorization to create them, their uniqueness i.e. you should only be able to create one badge with the same key/icon
**Additional context**
this is what the mutation looks like
```
mutation {
    CreateBadge(
      id: "${id}",
      key: "${key}",
      type: ${type},
      status: ${status},
      icon: "${icon}"
    ) { id }
  }
```
here are the types from the `schema.graphql`
```
type Badge {
  id: ID!
  key: String!
  type: BadgeTypeEnum!
  status: BadgeStatusEnum!
  icon: String!

  rewarded: [User]! @relation(name: "REWARDED", direction: "OUT")
}

enum BadgeTypeEnum {
  role
  crowdfunding
}
enum BadgeStatusEnum {
  permanent
  temporary
}
```

**Comment by roschaefer** [comment]
@mattwr18 You could explain *why* you want the badge to be unique and require permissions to create them. That would go into the **problem** section.
