### ISSUE TITLE
[WIP][Tests] Add backend tests for follows

### ISSUE THREAD

**Issue by Tirokk** [Human-Connection/Nitro-Backend#218]
**Is your feature request related to a problem? Please describe.**
- It has to be tested that `FOLLOWS` are not a multiple relation in the same direction.
- There should not be a self follow.

**Describe the solution you'd like**
Write resolvers and resolver tests.

**Describe alternatives you've considered**
I see none.

**Additional context**

@mattwr18 @tansaku @appinteractive @roschaefer @Lulalaby 

I guess:
- *The follow is a single sided relation. It can be from both sides, but that has nothing to do with each other.*
- *There is no metadata for a follow. Means we do not store the date of its invocation.*

**Comment by appinteractive** [comment]
I don’t get it, there are tests for it already. Or did I missed something? 🧐

**Comment by Tirokk** [comment]
Should have looked in your `shout and follow` PR @appinteractive …
I missed something … 😂
