### ISSUE TITLE
Update github README with latest documentation

### ISSUE THREAD

**Issue by aonomike** [Human-Connection/Nitro-Backend#226]
Currently the github README is not up to date.
It would be nice to have this updated with the latest documentation from [here](https://docs.human-connection.org/nitro/backend/installation/local-backend) so one could just get setup with the README.

**Comment by appinteractive** [comment]
The readme should not get to big. For details we should always refer to the main docs https://docs.human-connection.org/nitro/ 

But it should be very clear so everyone can get started quickly.

**Comment by Lulalaby** [comment]
I'll take over this.
Anyway it was and is planned already, so i'll close this issue.

**Comment by appinteractive** [comment]
@Lulalaby what do you mean with it’s planned already? Do you have some reference?

**Comment by Lulalaby** [comment]
I talked with @roschaefer that i'll enhance some things like the documentation, the readme and other things.

**Comment by roschaefer** [comment]
@Lulalaby try to be more specific, people don't know what we talked about.

Actually I don't even know what you mean :thinking: what did we talk about?
