### ISSUE TITLE
JWT strategy has an if-condition which is always true

### ISSUE THREAD

**Issue by roschaefer** [Human-Connection/Nitro-Backend#41]
**Describe the bug**
We have an if condition that always returns `true` [here](https://github.com/Human-Connection/Nitro-Backend/blob/master/src/jwt/strategy.js#L23). I guess we have to call neo4j on that line.

**To Reproduce**
I don't know how to reproduce a faulty behaviour. I checked if there is a different behaviour if I send
```json
{
  "Authorization": "Bearer whatever"
}
```
But there is no difference in behaviour. I guess it's because we're not checking the user at all.

**Expected behavior**
I never want to see `if(true)` anywhere in the code.

**Additional context**
Eslint gave me the error on commit f00dbb67dfec192dd470483230fb862b62cbbe9a:
```
yarn run eslint
```

**Comment by appinteractive** [comment]
That’s an issue for witch https://github.com/Human-Connection/Nitro-Web/issues/7 exists.
