### ISSUE TITLE
Optimize / Overwrite Mutations

### ISSUE THREAD

**Issue by appinteractive** [Human-Connection/Nitro-Backend#96]
Currently we have to attach related data with seperate calls to the api. Idealy that should be done automatically to maintain data integraty. For example, we should be able to ralate a newly created comment directly with a post instead of having to bind it seperatly.

Example:
```
mutation {
  CreateComment(content:"bla", resource:{id:"p1", type:"post"}) {
    id
    content
  }
}
```

**Comment by roschaefer** [comment]
We're already implementing some custom resolvers
